### PR TITLE
refactor: grouped files based on language and added corresponding links to README.md 

### PR DESCRIPTION
**Pull request by Ansh-Sarkar**
## Changes

Sorted the files into respective folders based on their language and updated ```README.md``` to contain a list of all files under each folder in order to give a sort of snapshot into the contents of the folder.

**Closes :** #5

### CODE REVIEW

**Comment by Sahiljawale** [comment]
Links in readme.md are taking to your forked repository  @Ansh-Sarkar

**Comment by Ansh-Sarkar** [comment]
Aah ok. My apologies. Will fix that.

**Comment by Ansh-Sarkar** [comment]
I'll just open another PR for fixing the links. Sorry for the issue.

**Comment by Sahiljawale** [comment]
Ok , Go ahead @Ansh-Sarkar

**Pull request merged**
